---
swagger: "2.0"
info:
  description: "For the Production Metrics project"
  version: "0.0.1"
  title: "Playground Application"
basePath: "/api"
schemes:
- "https"
paths:
  /one:
    get:
      summary: "One."
      description: "The one."
      operationId: "one_get"
      parameters: []
      responses:
        200:
          description: "1"
          schema:
            $ref: "#/definitions/Number"
      x-swagger-router-controller: "playground_application.controllers.default_controller"
  /two:
    get:
      summary: "Two."
      description: "The two."
      operationId: "two_get"
      parameters: []
      responses:
        200:
          description: "2"
          schema:
            $ref: "#/definitions/Number"
      x-swagger-router-controller: "playground_application.controllers.default_controller"
  /three:
    get:
      summary: "Three."
      description: "The three."
      operationId: "three_get"
      parameters: []
      responses:
        200:
          description: "3"
          schema:
            $ref: "#/definitions/Number"
      x-swagger-router-controller: "playground_application.controllers.default_controller"
definitions:
  Number:
    required:
    - "i"
    properties:
      i:
        type: "integer"
    example:
      i: 0
